"""Add status column to orders

Revision ID: 099a2334fe61
Revises: 793e243bc9ba
Create Date: 2025-02-26 16:27:40.768622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099a2334fe61'
down_revision = '793e243bc9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
