"""Recreate migrations

Revision ID: 49ad7ed7b97d
Revises: 
Create Date: 2025-03-18 23:08:40.773813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ad7ed7b97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sales', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_sales')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_seller')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
