"""Fixed created_at column

Revision ID: 6980e4b31b82
Revises: 49ad7ed7b97d
Create Date: 2025-03-18 23:15:20.724762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6980e4b31b82'
down_revision = '49ad7ed7b97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_sales', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_sales')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_seller')

    # ### end Alembic commands ###
