"""Description of changes

Revision ID: 9cfa65662de0
Revises: d73fc1c42033
Create Date: 2025-03-31 12:49:02.300956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cfa65662de0'
down_revision = 'd73fc1c42033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('HOME', 'WORK', 'OTHER', name='addresstype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_type',
               existing_type=sa.Enum('HOME', 'WORK', 'OTHER', name='addresstype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
